module.exports = {
    available_stock: {
        stock: [
            { id: 0, sku: 0, source: 0, capacity: 10 }, 
            { id: 1, sku: 1, source: 0, capacity: 10 }, 
            { id: 2, sku: 2, source: 0, capacity: 10 }, 
            { id: 3, sku: 3, source: 0, capacity: 10 }, 
            { id: 4, sku: 4, source: 0, capacity: 10 }, 
            { id: 5, sku: 0, source: 1, capacity: 10 }, 
            { id: 6, sku: 1, source: 1, capacity: 10 }, 
            { id: 7, sku: 2, source: 1, capacity: 10 }, 
            { id: 8, sku: 3, source: 1, capacity: 10 }, 
            { id: 9, sku: 4, source: 1, capacity: 10 }, 
            { id: 10, sku: 0, source: 2, capacity: 10 }, 
            { id: 11, sku: 1, source: 2, capacity: 10 }, 
            { id: 12, sku: 2, source: 2, capacity: 10 }, 
            { id: 13, sku: 3, source: 2, capacity: 10 }, 
            { id: 14, sku: 4, source: 2, capacity: 10 }, 
            { id: 15, sku: 0, source: 3, capacity: 10 }, 
            { id: 16, sku: 1, source: 3, capacity: 10 }, 
            { id: 17, sku: 2, source: 3, capacity: 10 }, 
            { id: 18, sku: 3, source: 3, capacity: 10 }, 
            { id: 19, sku: 4, source: 3, capacity: 10 }, 
            { id: 20, sku: 0, source: 4, capacity: 10 }, 
        ],
        demand: [
            { id: 0, sku: 0, target: 0, demand: 10 }, 
            { id: 1, sku: 1, target: 0, demand: 10 }, 
            { id: 2, sku: 2, target: 0, demand: 10 }, 
            { id: 3, sku: 3, target: 0, demand: 10 }, 
            { id: 4, sku: 4, target: 0, demand: 10 }, 
            { id: 5, sku: 0, target: 1, demand: 10 }, 
            { id: 6, sku: 1, target: 1, demand: 10 }, 
            { id: 7, sku: 2, target: 1, demand: 10 }, 
            { id: 8, sku: 3, target: 1, demand: 10 }, 
            { id: 9, sku: 4, target: 1, demand: 10 }, 
            { id: 10, sku: 0, target: 2, demand: 10 }, 
            { id: 11, sku: 1, target: 2, demand: 10 }, 
            { id: 12, sku: 2, target: 2, demand: 10 }, 
            { id: 13, sku: 3, target: 2, demand: 10 }, 
            { id: 14, sku: 4, target: 2, demand: 10 }, 
            { id: 15, sku: 0, target: 3, demand: 10 }, 
            { id: 16, sku: 1, target: 3, demand: 10 }, 
            { id: 17, sku: 2, target: 3, demand: 10 }, 
            { id: 18, sku: 3, target: 3, demand: 10 }, 
            { id: 19, sku: 4, target: 3, demand: 10 }, 
            { id: 20, sku: 0, target: 4, demand: 10 }, 
        ]
    },
    trigger_optimization: {
        dynamic_allocation: [
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
            { sku: 0, source: 0, target: 0, transfer: 0},
        ]
    }
}