apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: air-da-client
  name: air-da-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: air-da-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/air-da-network: "true"
        io.kompose.service: air-da-client
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/acn-gcda/multi-cloud/air-da-client:tag1
          name: air-da-client
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
