# apiVersion: v1
# kind: Namespace
# metadata:
#   name: retaildemo
#   labels:
#     name: retaildemo

# ---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: retaildemo
data:
  nginx.conf: |
      server {
        # Running port
        listen 5000;
        server_name  localhost;

        location / {          
          root /usr/share/nginx/html;
          try_files $uri $uri/ =404; 
        }

        location ~ ^/api {
          set $backend_name backend-service;
          set $namespace retaildemo;
          
          resolver kube-dns.kube-system.svc.cluster.local valid=5s;

          proxy_pass http://$backend_name.$namespace.svc.cluster.local$uri$is_args$args;
          proxy_set_header Host $host;
        }
      }