version: '3'
services:
  air-da-client:
    build: client
    image: air-da-client
    container_name: air-da-client
    ports:
      - 80:80
    networks:
      - air-da-network

  air-da-server:
    build: server
    ports:
      - 5000:5000
    image: air-da-server
    container_name: air-da-server
    networks:
      - air-da-network

networks:
  air-da-network:
    driver: bridge
